name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      # Add a simple HTTP service for testing
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 8080:80
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: 'npm'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        cd screencastcms
        pip install -r requirements.txt
        pip install requests
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Start Django Backend
      run: |
        cd screencastcms
        python manage.py migrate
        python manage.py collectstatic --noinput || echo "Static files collection skipped"
        python manage.py runserver 8001 &
        echo $! > django.pid
        sleep 10
        echo "Django server started"
    
    - name: Start Node.js Frontend
      run: |
        npm start &
        echo $! > nodejs.pid
        sleep 5
        echo "Node.js server started"
    
    - name: Test Django Backend Health
      run: |
        echo "🔍 Testing Django backend..."
        # Test Django admin (should redirect to login)
        if curl -f -s http://localhost:8001/admin/ > /dev/null; then
          echo "✅ Django admin accessible"
        else
          echo "⚠️ Django admin not accessible (may be normal)"
        fi
        
        # Test Django API endpoints
        if curl -f -s http://localhost:8001/api/ > /dev/null 2>&1; then
          echo "✅ Django API accessible"
        else
          echo "⚠️ Django API endpoint not found (may not be configured)"
        fi
    
    - name: Test Node.js Frontend Health
      run: |
        echo "🔍 Testing Node.js frontend..."
        if curl -f -s http://localhost:3000 > /dev/null; then
          echo "✅ Node.js frontend accessible"
        else
          echo "❌ Node.js frontend not accessible"
          exit 1
        fi
        
        # Test specific routes
        routes=("/" "/projects" "/skills" "/experience" "/contact")
        for route in "${routes[@]}"; do
          if curl -f -s "http://localhost:3000$route" > /dev/null; then
            echo "✅ Route $route accessible"
          else
            echo "⚠️ Route $route not accessible (may not be implemented)"
          fi
        done
    
    - name: Test Frontend-Backend Integration
      run: |
        echo "🔍 Testing frontend-backend integration..."
        
        # Test if frontend can reach backend
        python3 -c "
import requests
import time
import sys

try:
    # Test Django backend
    django_response = requests.get('http://localhost:8001/', timeout=5)
    print(f'✅ Django backend responding with status: {django_response.status_code}')
    
    # Test Node.js frontend
    nodejs_response = requests.get('http://localhost:3000/', timeout=5)
    print(f'✅ Node.js frontend responding with status: {nodejs_response.status_code}')
    
    print('✅ Integration test passed')
except requests.exceptions.RequestException as e:
    print(f'⚠️ Integration test warning: {e}')
    # Don't fail the build for integration issues
except Exception as e:
    print(f'❌ Integration test error: {e}')
    sys.exit(1)
        "
    
    - name: Cleanup
      if: always()
      run: |
        echo "🧹 Cleaning up processes..."
        if [ -f django.pid ]; then
          kill $(cat django.pid) || true
          rm django.pid
        fi
        if [ -f nodejs.pid ]; then
          kill $(cat nodejs.pid) || true
          rm nodejs.pid
        fi
        # Kill any remaining processes
        pkill -f "python manage.py runserver" || true
        pkill -f "node index.js" || true
        echo "✅ Cleanup completed"
